# Generated by Django 4.2.4 on 2023-08-22 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='multimedia/')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImagenesApp.archivo')),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('archivos', models.ManyToManyField(through='ImagenesApp.DetallePresentacion', to='ImagenesApp.archivo')),
            ],
        ),
        migrations.AddField(
            model_name='detallepresentacion',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImagenesApp.presentacion'),
        ),
    ]
