# Generated by Django 4.2.4 on 2023-08-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagenesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
