# Generated by Django 4.2.4 on 2023-08-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagenesApp', '0002_alter_archivo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
