# Generated by Django 4.2.4 on 2023-08-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagenesApp', '0004_presentacion_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='tipo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to='archivos/'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
