# Generated by Django 4.2.4 on 2023-08-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagenesApp', '0007_remove_archivo_es_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='miniaturas/'),
        ),
    ]
