# Generated by Django 4.2.4 on 2023-08-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagenesApp', '0008_archivo_miniatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='miniatura',
        ),
        migrations.AddField(
            model_name='archivo',
            name='es_video',
            field=models.BooleanField(default=False),
        ),
    ]
